config/routes.rb
Rails.application.routes.draw do
  root 'list#index'
  get 'list/index' => redirect("/")

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :events,       only: [:show]
  resources :reservations, only: [:show, :new, :create]
  resources :customers,    only: [:show, :new, :create]

  root to:'list#index', as:'list'
end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  name       :string
#  tel        :string
#  address    :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Customer < ActiveRecord::Base
  has_many :reservations

  validates :name, presence: true
  validates :tel, presence: true
  validates :address, presence: true
  validates :email, presence: true
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  date        :datetime
#  stock_count :integer
#  price       :integer
#  sell_count  :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Event < ActiveRecord::Base
  has_many :reservations

  validates :title, presence: true
  validates :description, presence: true
  validates :date, presence: true
  validates :stock_count, presence: true
  validates :price, presence: true
  validates :sell_count, presence: true
end

app/models/reservation.rb
# == Schema Information
#
# Table name: reservations
#
#  id          :integer          not null, primary key
#  customer_id :integer
#  event_id    :integer
#  buy_count   :integer
#  payment     :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Reservation < ActiveRecord::Base
  PAYMENT_TYPES = [ "現金", "銀行振込", "クレジットカード" ]

  belongs_to :customer
  belongs_to :event

  validates :customer_id, presence: true
  validates :event_id, presence: true
  validates :buy_count, presence: true
  validates :payment, inclusion: PAYMENT_TYPES
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < InheritedResources::Base

  private

    def customer_params
      params.require(:customer).permit(:name, :tel, :address, :email)
    end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def index
  end
end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base

  def show
    @event = Event.find(params[:id])
  end

  private

    def event_params
      params.require(:event).permit(:title, :description, :date, :stock_count, :price, :sell_count)
    end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  def index
    @eventlists = Event.order(:date)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < InheritedResources::Base

  private

    def reservation_params
      params.require(:reservation).permit(:customer_id, :event_id, :buy_count, :payment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'お名前' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label 'ご連絡先' %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label 'ご住所' %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label 'メールアドレス' %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>お客様一覧表</h1>

<table>
  <thead>
    <tr>
      <th>お名前</th>
      <th>ご連絡先</th>
      <th>ご住所</th>
      <th>メールアドレス</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.tel %></td>
        <td><%= customer.address %></td>
        <td><%= customer.email %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>お客様情報入力フォーム</h1>

<%= render 'form' %>

<%= button_to 'イベント一覧へ戻る', list_path, method: :get %>

app/views/customers/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<p>
  <strong>お名前：</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>ご連絡先：</strong>
  <%= @customer.tel %>
</p>

<p>
  <strong>ご住所：</strong>
  <%= @customer.address %>
</p>

<p>
  <strong>メールアドレス：</strong>
  <%= @customer.email %>
</p>

<%#= link_to 'Edit', edit_customer_path(@customer) %>
<%#= link_to 'Back', customers_path %>
<p><%= button_to '予約入力へ', new_reservation_path, method: :get %><p>
<p><%= button_to 'イベント一覧へ戻る', list_path, method: :get %><p>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'イベント名' %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label '詳細情報' %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label '日程' %><br>
    <%= f.datetime_select :date, :start_year => 2015 %>
  </div>
  <div class="field">
    <%= f.label '上限枚数' %><br>
    <%= f.number_field :stock_count %>
  </div>
  <div class="field">
    <%= f.label '金額' %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label '予約枚数' %><br>
    <%= f.number_field :sell_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>イベント一覧表</h1>

<table>
  <thead>
    <tr>
      <th>イベント名</th>
      <th>詳細情報</th>
      <th>日程</th>
      <th>上限枚数</th>
      <th>金額</th>
      <th>予約枚数</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.date %></td>
        <td><%= event.stock_count %></td>
        <td><%= number_to_currency(event.price, :unit => "円", :precision => 0) %></td>
        <td><%= event.sell_count %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>イベント名:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>詳細情報:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>日程:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>上限枚数:</strong>
  <%= @event.stock_count %>
</p>

<p>
  <strong>金額:</strong>
  <%= number_to_currency(@event.price, :unit => "円", :precision => 0) %>
</p>

<p>
  <strong>予約枚数:</strong>
  <%= @event.sell_count %>
</p>

<p><%= button_to '申込ページへ', new_customer_path, method: :get %></p>
<p><%= button_to 'イベント一覧へ戻る', list_path, method: :get %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ResrvTicket</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<% if notice.present? %>

  <p class="notice"><%= notice %></p>

<% end %>

<% if alert.present? %>

  <p class="alert"><%= alert %></p>

<% end %>
</body>
</html>

app/views/list/index.html.erb
<link rel="stylesheet" type="text/css" href="style.css" id="mystyle">

<script src="https://dzpp79ucibp5a.cloudfront.net/assets/www-40623f933e5adec936dfab1ee5dccde8e3c72f458d9a09d6be63d199ea2ba60e.js" async="async"></script>
<div class="navbar navbar-static-top navbar-inverse full-min-width">
  <div class="navbar-inner">
    <div class="container">
      <a href="https://www.doorkeeper.jp/" class="brand doorkeeper"><img width="194" height="29" src="" alt="インデックス"></a>
      <a data-toggle="collapse" data-target=".nav-collapse" class="btn btn-navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a><!--
      <div class="container nav-collapse">
        <ul class="nav pull-right">
          <li><a href="">新規登録</a></li>
          <li><a href="">ログイン</a></li>
        </ul>
      </div>
    -->
  </div>
</div>
<div class="content">
  <div class="container">
    <div class="row">
      <div class="span12">
        <div class="page-header">
          <h1>イベント情報一覧</h1>
        </div>
        <hr>
        <% @eventlists.each do |eventlist| %>
        <div class="infinite-scroll">
          <div class="content event-list">
            <h5>開催日時：<time itemprop="startDate" datetime=""><%= eventlist.date.to_s %></time></h5>
            <div itemtype="" itemscope="" class="row-fluid event-listed">
              <div class="span11">
                <h2><%= eventlist.title %></h2>
              </div>
            </div>
            <p class="large">イベント内容：<%= sanitize(eventlist.description) %></p>
            <p itemtype="" itemscope="" itemprop="location">
              <span itemprop="address" class="muted">金額：<%= number_to_currency(eventlist.price, :unit => "円", :precision => 0) %></span>
              <%= button_to '詳細・申込ページへ', event_path(eventlist.id), method: :get %>
            </p>
            <hr>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

  <div class='container'>
    <div class='row'>
      <div class='span3'>
        <h4>チケット予約サイト</h4>
        <ul class='unstyled'>
          <li><a href="">料金</a></li>
          <li><a href="">会社概要</a></li>
          <li><a href="">ヘルプ</a></li>
        </li>
      </ul>
    </div>
    <div class='span3'>
      <h4>リソース</h4>
      <ul class='unstyled'>
        <li><a href="">イベント企画</a></li>
        <li><a href="">会場</a></li>
        <li><a href="">API</a></li>
        <li><a href="">イベント一覧</a></li>
      </ul>
    </div>
    <div class='span3'>
      <h4>ポリシー</h4>
      <ul class='unstyled'>
        <li><a href="">利用規約</a></li>
        <li><a href="">プライバシーポリシー</a></li>
        <li><a href="">セキュリティ</a></li>
        <li><a href="">特定商取引法に基づく表記</a></li>
      </ul>
    </div>
    <div class='span3'>
      <h4>最新情報</h4>
      <ul class='unstyled'>
        <li>
          <a href="https://www.facebook.com/"><i class='icon-facebook'></i>
            Facebook
          </a></li>
          <li>
            <a href="https://twitter.com/"><i class='icon-twitter'></i>
              Twitter
            </a></li>
          </ul>
        </div>
      </div>
    </div>


  <script>

</script>

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'お客様名' %><br>
    <%= f.number_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label 'イベント名' %><br>
    <%#= f.number_field :event_id %>
    <%= f.collection_select(:event_id, Event.all, :id, :title) %>
  </div>
  <div class="field">
    <%= f.label '購入枚数' %><br>
    <%= f.number_field :buy_count %>
  </div>
  <div class="field">
    <%= f.label 'お支払方法' %><br>
    <%= f.select(:payment, options_for_select(["現金", "銀行振込", "クレジットカード"])) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>予約一覧表</h1>

<table>
  <thead>
    <tr>
      <th>お客様名</th>
      <th>イベント名</th>
      <th>購入枚数</th>
      <th>お支払方法</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.customer.name %></td>
        <td><%= reservation.event.title %></td>
        <td><%= reservation.buy_count %></td>
        <td><%= reservation.payment %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>イベント予約入力フォーム</h1>

<%= render 'form' %>

<%= button_to 'イベント一覧へ戻る', list_path, method: :get %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>お客様名:</strong>
  <%= @reservation.customer.name %>
</p>

<p>
  <strong>イベント名:</strong>
  <%= @reservation.event.title %>
</p>

<p>
  <strong>購入枚数:</strong>
  <%= @reservation.buy_count %>
</p>

<p>
  <strong>お支払方法:</strong>
  <%= @reservation.payment %>
</p>

<%#= link_to 'Edit', edit_reservation_path(@reservation) %>
<%#= link_to 'Back', reservations_path %>

<%= button_to 'イベント一覧へ戻る', list_path, method: :get %>